apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-prod
resources:
  - ../../base
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: typescript-app-example
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: typescript-app-example.homelab.swhurl.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: typescript-app-example.homelab.swhurl.com
      - op: add
        path: /metadata/annotations
        value:
          traefik.ingress.kubernetes.io/router.middlewares: ingress-oauth-auth-shared@kubernetescrd
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: typescript-app-example
    patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: typescript-app-example.homelab.swhurl.com
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: typescript-app-example
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: "service.namespace=apps,deployment.environment=prod"
