apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: typescript-app-example
  namespace: apps-staging
  labels:
    app.kubernetes.io/name: typescript-app-example
    app.kubernetes.io/instance: typescript-app-example
    platform.swhurl.com/managed: "true"
spec:
  secretName: typescript-app-example-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - staging-typescript-app-example.homelab.swhurl.com

