apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-staging
resources:
  - ../../base
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: typescript-app-example
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          traefik.ingress.kubernetes.io/router.middlewares: ingress-oauth-auth-shared@kubernetescrd
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: typescript-app-example
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: "service.namespace=apps,deployment.environment=staging"
